spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_investment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: your-secret-key-here-make-it-very-long-and-secure-in-production
      expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8080

logging:
  level:
    com.microinvestment: DEBUG
    org.springframework.security: DEBUG 